# Generated by Django 5.0.2 on 2024-02-19 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='thedevu101-admin-media/user-default.png', null=True, upload_to='thedevu101-admin-media/profile-pictures/'),
        ),
    ]
