# Generated by Django 5.0.3 on 2024-03-30 20:09

import app_main.validators
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('owner_fullname', models.CharField(blank=True, max_length=200, null=True, verbose_name="O'qituvchi")),
                ('name', models.CharField(max_length=200, verbose_name='Nima uchun')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[app_main.validators.expense_amount_validator], verbose_name="Miqdor (so'mda)")),
                ('note', models.TextField(blank=True, null=True, verbose_name="Qo'shimcha ma'lumot")),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name="To'lov vaqti")),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name="O'zgartirilgan vaqt")),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Guruh nomi')),
                ('price', models.IntegerField(validators=[app_main.validators.min_value_validator], verbose_name="Guruh to'lovi")),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('owner_fullname', models.CharField(blank=True, max_length=200, null=True)),
                ('month', models.DateField(max_length=200, null=True, verbose_name="To'lov oyi")),
                ('pupil_fullname', models.CharField(blank=True, max_length=200, null=True)),
                ('group_name', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.IntegerField(verbose_name="To'lov")),
                ('note', models.TextField(blank=True, null=True, verbose_name="Eslatma / To'lov tarifi")),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name="To'lov vaqti")),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name="O'zgartirilgan vaqt")),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ('-month', 'pupil_fullname', 'pupil', 'amount'),
            },
        ),
        migrations.CreateModel(
            name='Pupil',
            fields=[
                ('first_name', models.CharField(max_length=200, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=200, verbose_name='Familiya')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('name', models.CharField(max_length=200, unique=True, validators=[app_main.validators.subject_name_length_validator], verbose_name='Fan nomi')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ['name', 'created'],
            },
        ),
    ]
